model:
  name: resnet18
  pretrained: True

optimizer:
  type: SGD
  lr: 0.003
  momentum: 0.9

scheduler:
  step_size: 7
  gamma: 0.1

training:
  epochs: 50

data:
  augmentation:
    train: default
    test: default, gaussian blur, gaussian noise, random affine


  dir:
    train: ./train/
    valid: ./valid/
    test: ./test/

